### ISSUE TITLE
Trinidad and Tobago Frequency should be US915

### ISSUE THREAD

**Issue by Wezy904** [gradoj/hplans#11]
![Screenshot 2021-12-16 145309](https://user-images.githubusercontent.com/81589742/146431435-94884a7d-488b-4a63-8b7a-5a8f075ad7ed.jpg)

To whom it may concern,
                                        I have had correspondence with LoRa Alliance regarding the frequency use for Trinidad and Tobago. They advised the following 👍 

"A foot note was lost during the editorial process of 1.0.3 which is used to indicate that US902-928 is indeed a valid channel plan for Trinidad and Tobago.  The Regional Parameters workgroup continues to recommend AU915 for harmony with the other countries in the Caribbean and  Central and South America, many of which do not support the 902-915 portion of the US band. "

As such, please revise the recognised Frequency to US915 for Trinidad and Tobago,  as its recognized as AU915 ONLY

![Screenshot 2021-12-16 144241](https://user-images.githubusercontent.com/81589742/146431802-affd5c88-dea5-487b-bfbe-541f93c2b33b.jpg)

**Comment by gradoj** [comment]
i will just keep it as AU915 for now as it is in the latest semtech regional parameters and still recommended. AU915 was also in https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv#L222
I would suggest bringing it forward after hip45 has been implemented. US915 hardware should be compatible and auto switch to AU915.

**Comment by Wezy904** [comment]
Email from The Telecommunications Authority of Trinidad and Tobago, dated 16th November, 2021

![Screenshot 2021-12-18 022326](https://user-images.githubusercontent.com/81589742/146631693-256cb1dc-aa9e-43d3-80cf-850c3646a18b.jpg)

"As discussed, the Telecommunications Authority of Trinidad and Tobago (TATT) has authorised the use of LoraWAN devices in Trinidad and Tobago. The use of these devices a covered by a class licence and therefore, all devices that operate in accordance with the technical operational limits established by TATT will be certified for use in Trinidad and Tobago.

 

The technical operational limits are defined in the Schedule of Devices Eligible for Use Under a Class Licence, see attached. I also include a link below to the webpage where this document can be found on TATT’s website.

 

https://tatt.org.tt/Licensing/ClassLicence.aspx "

"As you can see, these devices can operate in the frequency range 902-928 MHz. Therefore, there is no restriction to either the US or AU channel plans. You can request from the LoRa Alliance that Trinidad and Tobago is recognised for the US and AUS channel plans. "

Based on the direction of our regulated authority, I believe it would be best to implement BOTH US915 and AU915, as intended by T.A.T.T.  It is clear that the spectrum allocation is 902-928 Mhz.

**Comment by gradoj** [comment]
Helium has intentions of supporting multiple channel plans, however, at this time only one must be selected and used. I will leave it as AU but I added US915 into the regions.csv file as an alternate that is not currently used for future.
