### ISSUE TITLE
Malta No Longer Beaconing or Witnessing

### ISSUE THREAD

**Issue by J0SHINAT0R** [gradoj/hplans#14]
For some reason since the 14th of December, all hotspots in Malta (EU) have simply stopped sending out beacons and witnessing eachother.

**Comment by gradoj** [comment]
Malta is in the EU868 geojson polygons but does not appear in the h3idx hexes that went in the miner for pocv11. I regenerated them and it is correct. This will get updated next miner release. Looks like the lorawan-h3 needed an update.
![image](https://user-images.githubusercontent.com/7544765/146653638-d6656e97-eb63-41c1-9433-25fc6caf83d8.png)
This can be closed after it is confirmed to have made it into https://github.com/helium/lorawan-h3/tree/main/serialized

**Comment by J0SHINAT0R** [comment]
Thanks so much for your quick response.  

So what would be the approximate time estimate for the above update to take place?

As obviously all our hotspots are pretty much useless until its fixed & and everyone is asking me for updates at this point haha

I look forward to your reply.

Thanks.

**Comment by claydon99** [comment]
> Malta is in the EU868 geojson polygons but does not appear in the h3idx hexes that went in the miner for pocv11. I regenerated them and it is correct. This will get updated next miner release. Looks like the lorawan-h3 needed an update.
> ![image](https://user-images.githubusercontent.com/7544765/146653638-d6656e97-eb63-41c1-9433-25fc6caf83d8.png)
> This can be closed after it is confirmed to have made it into https://github.com/helium/lorawan-h3/tree/main/serialized

Any updates ?? As issue hasn’t been fixed yet

**Comment by gradoj** [comment]
This should be addressed. Someone confirm and this can be closed.

**Comment by J0SHINAT0R** [comment]
Yes, i can confirm that this has been addressed. Thanks
