### ISSUE TITLE
Update Guyana to US915

### ISSUE THREAD

**Issue by the-wildcard** [gradoj/hplans#17]
While the RP2-1.0.3 LoRaWAN® Regional Parameters are currently silent on Guyana, the National Frequency Allocation table permits amateur use on 902-928 MHz. Update Guyana frequency from unknown to US915.

https://telecoms.gov.gy/resources/National%20Frequency%20Allocation%20Table%20for%20Guyana.pdf

**Comment by gradoj** [comment]
even though the semtech regional parameters have no channel plan the original file had Guyana as US915 https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv

I will update the regional to US915
