### ISSUE TITLE
Duplicate lines in list - Vatican

### ISSUE THREAD

**Issue by waveform06** [gradoj/hplans#20]
Vatican is in list twice.

Under (H) Holy See as EU868
Under (V) Vatican as Unknown

As the Vatican is only 1km wide and in the middle of the EU868 Italy region I would think EU868 Is correct.

**Comment by gradoj** [comment]
![image](https://user-images.githubusercontent.com/7544765/149705595-05652968-9f42-4427-baaf-c8c935e1d3da.png)
The EU868 version is currently what is in use.
