### ISSUE TITLE
Aruba should have 'unknown' channel plan 

### ISSUE THREAD

**Issue by gradoj** [gradoj/hplans#7]
![image](https://user-images.githubusercontent.com/7544765/145931014-076f1fab-a9d9-4540-9d0b-357803d6a267.png)

Aruba shows up as EU868 in the polygons even though it should be 'unknown' according to the csv. This is happening because Aruba is part of the Netherlands from the openmaps dataset. 

Aruba and Curacoa are the only two cases where this happens that i know of. They are a different channel region from their region as downloaded from openmaps.

**Comment by kitachi15** [comment]
hi,
After the POCv11 update, all hotspots in Aruba and Curacao (US915) suddenly got ALL invalid witnessed beacons because of incorrect_frequency.
