### ISSUE TITLE
Philippines Should be AS923-3

### ISSUE THREAD

**Issue by rvjaywaks** [gradoj/hplans#8]
After the POCv11, hotspots in the Philippines (AS923-3) suddenly got ALL invalid beacons and witnesses. There was no change in the frequency when the upgrade to POCv11 happened. It was still the the same AS923-3 uplink frequencies but those are now incorrect_frequency. Did we missed something in the config file or something related to that?

https://explorer.helium.com/txns/HnsJUI1mtfFbs-A-wAAIxPoWK6slCuybLhXOUmuz93A

Here's the screenshot of the frequency and the invalid witnessing caused by incorrect_frequency.

I hope the helium team can have a look and make the fix soon.

**Comment by shockool** [comment]
hi team, i would like to raise this same concern as well as I am part of the affected party, looking forward for a proper help about this, thanks!

**Comment by retsel86** [comment]
any progress on this? Philippine Region to AS923-3?

**Comment by rvjaywaks** [comment]
It also indicated in the helium documentation that Philippines is AS923.

https://docs.helium.com/lorawan-on-helium/frequency-plans/

hope you can resolve this is soon @gradoj. Thanks.

**Comment by jonroque** [comment]
what's the update on this? was just wondering how this happened, the fact that the specific region frequency was clearly published at the helium site as AS923-3 for Philippines.
